// <auto-generated />
using CourtBooking.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace CourtBooking.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260519200000_AddPlatformConfig")]
    partial class AddPlatformConfig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Minimal snapshot — EF only needs the [Migration] attribute to discover and apply this migration.
        }
    }
}
