// <auto-generated />
using CourtBooking.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace CourtBooking.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260519210000_AddBankQrToPlatformConfig")]
    partial class AddBankQrToPlatformConfig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder) { }
    }
}
