using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace CourtBooking.Migrations
{
    /// <inheritdoc />
    public partial class FixVoucherIdentityColumn : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // AddVouchers was scaffolded while only the SQLite provider was registered for
            // design-time model building (same root cause as FixAddOnRentalIdentityColumns),
            // so Vouchers.Id only got the "Sqlite:Autoincrement" annotation, never the Npgsql
            // identity-generation annotation every other int-Id table has. In Postgres that
            // left Id as a plain "integer NOT NULL" column with no sequence/default, so every
            // INSERT relying on the DB to generate Id failed with "null value in column Id
            // violates not-null constraint". SQLite is unaffected, so this only runs on Postgres.
            if (migrationBuilder.ActiveProvider == "Npgsql.EntityFrameworkCore.PostgreSQL")
            {
                migrationBuilder.Sql(
                    "ALTER TABLE \"Vouchers\" ALTER COLUMN \"Id\" ADD GENERATED BY DEFAULT AS IDENTITY;");
                migrationBuilder.Sql(
                    "SELECT setval(pg_get_serial_sequence('\"Vouchers\"', 'Id'), COALESCE((SELECT MAX(\"Id\") FROM \"Vouchers\"), 0) + 1, false);");
            }
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            if (migrationBuilder.ActiveProvider == "Npgsql.EntityFrameworkCore.PostgreSQL")
            {
                migrationBuilder.Sql(
                    "ALTER TABLE \"Vouchers\" ALTER COLUMN \"Id\" DROP IDENTITY IF EXISTS;");
            }
        }
    }
}
