// <auto-generated />
using System;
using CourtBooking.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CourtBooking.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260730164000_AddReservedUntilToBookingsAndSignups")]
    partial class AddReservedUntilToBookingsAndSignups
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            // This is intentionally left minimal as only columns are being added
#pragma warning restore 612, 618
        }
    }
}
