using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace CourtBooking.Migrations
{
    /// <inheritdoc />
    public partial class FixAddOnRentalIdentityColumns : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // AddAddOnRentals was scaffolded while only the SQLite provider was registered for
            // design-time model building, so it only emitted the "Sqlite:Autoincrement" annotation
            // on these Id columns — never the Npgsql identity-generation annotation that every other
            // int-Id table in this project has. In Postgres that meant Id was created as a plain
            // "integer NOT NULL" column with no sequence/default, so every INSERT that relies on the
            // DB generating Id fails with "null value in column Id violates not-null constraint".
            // SQLite is unaffected (its own autoincrement annotation was already correct), so this
            // only needs to run against Postgres.
            if (migrationBuilder.ActiveProvider == "Npgsql.EntityFrameworkCore.PostgreSQL")
            {
                migrationBuilder.Sql(
                    "ALTER TABLE \"AddOnRentals\" ALTER COLUMN \"Id\" ADD GENERATED BY DEFAULT AS IDENTITY;");
                migrationBuilder.Sql(
                    "SELECT setval(pg_get_serial_sequence('\"AddOnRentals\"', 'Id'), COALESCE((SELECT MAX(\"Id\") FROM \"AddOnRentals\"), 0) + 1, false);");

                migrationBuilder.Sql(
                    "ALTER TABLE \"AddOnRentalItems\" ALTER COLUMN \"Id\" ADD GENERATED BY DEFAULT AS IDENTITY;");
                migrationBuilder.Sql(
                    "SELECT setval(pg_get_serial_sequence('\"AddOnRentalItems\"', 'Id'), COALESCE((SELECT MAX(\"Id\") FROM \"AddOnRentalItems\"), 0) + 1, false);");
            }
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            if (migrationBuilder.ActiveProvider == "Npgsql.EntityFrameworkCore.PostgreSQL")
            {
                migrationBuilder.Sql(
                    "ALTER TABLE \"AddOnRentals\" ALTER COLUMN \"Id\" DROP IDENTITY IF EXISTS;");
                migrationBuilder.Sql(
                    "ALTER TABLE \"AddOnRentalItems\" ALTER COLUMN \"Id\" DROP IDENTITY IF EXISTS;");
            }
        }
    }
}
